# Parameter name         | Parameter
# --==[ Main Font ]==--
# Основной шрифт
font_family      JetBrainsMono Nerd Font Regular
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font 
bold_italic_font JetBrainsMono Nerd Font Bold 

# --==[ Nerd Font ]==--
font_family                JetBrains Mono Nerd Font
bold_font                  JetBrainsMono Nerd Nerd Font Bold
italic_font                JetBrainsMono Nerd Nerd Font 
bold_italic_font           JetBrainsMono Nerd Nerd Font Bold 

font_size 12

# --==[ Ligatures ]==--
disable_ligatures never

# --==[ Transparency ]==--

background_opacity         0.9
dynamic_background_opacity no
inactive_text_alpha        0.9

# --==[ Window decoration ]==--
hide_window_decorations    titlebar-only 
window_padding_width       8                

#  .-===================-.
# <--==[ Ashen Theme ]==-->
#  `-===================-`

# --==[ Background and foreground ]==--
background                 #121212
foreground                 #B4B4B4
selection_background       #323232
selection_foreground       #E5E5E5

# --==[ Cursor ]==--
cursor                     #E49A44
cursor_text_color          #121212
cursor_shape               block    
cursor_blink_interval      0.2        

# --==[ ANSIcolors ]==--
color0                     #121212 # Black
color1                     #C53030 # Red
color2                     #4A8B8B # Green
color3                     #E5A72A # Yellow
color4                     #6FA8FF # Blue 
color5                     #B14242 # Magenta
color6                     #D87C4A # Cyan
color7                     #B4B4B4 # White

# --==[ Bright ANSI colors ]==--
color8                     #535353 # Black 
color9                     #DF6464 # Red
color10                    #7FBDBD # Green
color11                    #F1C04E # Yellow
color12                    #9BC4FF # Blue
color13                    #D06A6A # Magenta
color14                    #F0A35B # Cyan
color15                    #E5E5E5 # White

# --==[ Other parameters ]==--
scrollback_lines           5000
mouse_hide_wait            2.0  

term                       xterm-256color

enable_audio_bell          no
visual_bell_duration       0.0
